import time

import singer
import singer.utils as singer_utils
from requests.exceptions import RequestException
from singer import Transformer, metadata, metrics

from tap_salesforce import output as tap_output
from tap_salesforce.salesforce.bulk import Bulk

LOGGER = singer.get_logger()

BLACKLISTED_FIELDS = {"attributes"}


def remove_blacklisted_fields(data):
    return {k: v for k, v in data.items() if k not in BLACKLISTED_FIELDS}


# pylint: disable=unused-argument
def transform_bulk_data_hook(data, typ, schema):
    result = data
    if isinstance(data, dict):
        result = remove_blacklisted_fields(data)

    # Salesforce Bulk API returns CSV's with empty strings for text fields.
    # When the text field is nillable and the data value is an empty string,
    # change the data so that it is None.
    if data == "" and "null" in schema["type"]:
        result = None

    return result


def get_stream_version(catalog_entry, state):
    tap_stream_id = catalog_entry["tap_stream_id"]
    catalog_metadata = metadata.to_map(catalog_entry["metadata"])
    replication_key = catalog_metadata.get((), {}).get("replication-key")

    if singer.get_bookmark(state, tap_stream_id, "version") is None:
        stream_version = int(time.time() * 1000)
    else:
        stream_version = singer.get_bookmark(state, tap_stream_id, "version")

    if replication_key:
        return stream_version
    return int(time.time() * 1000)


def resume_syncing_bulk_query(sf, catalog_entry, job_id, state, counter):
    bulk = Bulk(sf)
    current_bookmark = singer.get_bookmark(
        state, catalog_entry["tap_stream_id"], "JobHighestBookmarkSeen"
    ) or sf.get_start_date(state, catalog_entry)
    current_bookmark = singer_utils.strptime_with_tz(current_bookmark)
    batch_ids = singer.get_bookmark(state, catalog_entry["tap_stream_id"], "BatchIDs")

    start_time = singer_utils.now()
    stream = catalog_entry["stream"]
    stream_alias = catalog_entry.get("stream_alias")
    catalog_metadata = metadata.to_map(catalog_entry.get("metadata"))
    replication_key = catalog_metadata.get((), {}).get("replication-key")
    stream_version = get_stream_version(catalog_entry, state)
    schema = catalog_entry["schema"]

    if not bulk.job_exists(job_id):
        LOGGER.info("Found stored Job ID that no longer exists, resetting bookmark and removing JobID from state.")
        return counter

    # Iterate over the remaining batches, removing them once they are synced
    for batch_id in batch_ids[:]:
        with Transformer(pre_hook=transform_bulk_data_hook) as transformer:
            for rec in bulk.get_batch_results(job_id, batch_id, catalog_entry):
                counter.increment()
                rec = transformer.transform(rec, schema)
                rec = fix_record_anytype(rec, schema)
                tap_output.write_record(
                    (stream_alias or stream),
                    rec,
                    version=stream_version,
                    time_extracted=start_time,
                )

                # Update bookmark if necessary
                replication_key_value = replication_key and singer_utils.strptime_with_tz(rec[replication_key])
                if (
                    replication_key_value
                    and replication_key_value <= start_time
                    and replication_key_value > current_bookmark
                ):
                    current_bookmark = singer_utils.strptime_with_tz(rec[replication_key])

        state = singer.write_bookmark(
            state,
            catalog_entry["tap_stream_id"],
            "JobHighestBookmarkSeen",
            singer_utils.strftime(current_bookmark),
        )
        batch_ids.remove(batch_id)
        LOGGER.info("Finished syncing batch %s. Removing batch from state.", batch_id)
        LOGGER.info("Batches to go: %d", len(batch_ids))
        tap_output.write_state(state)


def sync_stream(sf, catalog_entry, state, state_msg_threshold):
    stream = catalog_entry["stream"]

    with metrics.record_counter(stream) as counter:
        try:
            sync_records(sf, catalog_entry, state, counter, state_msg_threshold)
            # Write the state generated for the last record generated by sf.query
            tap_output.write_state(state)
        except RequestException as ex:
            raise Exception(f"Error syncing {stream}: {ex} Response: {ex.response.text}")  # noqa: B904
        except Exception as ex:
            raise Exception(f"Error syncing {stream}: {ex}") from ex


def empty_filtered_window(sf, catalog_entry, counter, replication_key):
    """Whether a row filter narrowed this stream's window and nothing came back.

    The bookmark only ever advances to the replication key of a record that was
    returned, so a window admitting no rows leaves it where it was: the next run
    re-issues the same `>= bookmark` query over a range one cycle wider, and keeps
    widening until Salesforce refuses it. The legacy puller instead advances to the end
    of the window it asked for and moves past empty windows, which is the behaviour to
    match here.

    Only filtered streams qualify. On an unfiltered stream an empty window means
    nothing was modified, which leaving the bookmark alone already handles correctly;
    advancing it there would change every stream's behaviour to fix a problem only a
    filter can create.
    """
    return counter.value == 0 and bool(replication_key) and sf.has_row_filter(catalog_entry)


def write_window_end_bookmark(state, catalog_entry, replication_key, start_time):
    """Advance the bookmark to the moment the query was issued.

    `start_time` is read before the query goes out, so it is never later than anything
    the query could have returned.

    It is a reading of our clock rather than a value Salesforce handed back, which is
    the one way this differs from the has-records path. A record whose replication key
    lands at or before `start_time` but which Salesforce had not yet made visible when
    the query ran would be skipped for good, and clock skew between this host and the
    org widens that window. The alternative is a stream whose cursor never moves again
    and whose scanned range grows every run, so this is the better of two exposures --
    and it is the same trade the legacy puller makes by advancing to the end of the
    window it requested.
    """
    from tap_salesforce import CONFIG

    stream = catalog_entry["stream"]
    return singer.write_bookmark(
        state,
        catalog_entry["tap_stream_id"],
        replication_key,
        tap_output.safe_bookmark_value(
            stream,
            replication_key,
            singer_utils.strftime(start_time),
            max_future_seconds=CONFIG.get("max_future_bookmark_seconds", 3600),
        ),
    )


def sync_records(sf, catalog_entry, state, counter, state_msg_threshold):
    from tap_salesforce import CONFIG

    chunked_bookmark = singer_utils.strptime_with_tz(sf.get_start_date(state, catalog_entry))
    stream = catalog_entry["stream"]
    schema = catalog_entry["schema"]
    stream_alias = catalog_entry.get("stream_alias")
    catalog_metadata = metadata.to_map(catalog_entry["metadata"])
    replication_key = catalog_metadata.get((), {}).get("replication-key")
    stream_version = get_stream_version(catalog_entry, state)
    activate_version_message = singer.ActivateVersionMessage(stream=(stream_alias or stream), version=stream_version)

    start_time = singer_utils.now()

    LOGGER.info("Syncing Salesforce data for stream %s", stream)

    for rec in sf.query(catalog_entry, state):
        counter.increment()
        with Transformer(pre_hook=transform_bulk_data_hook) as transformer:
            rec = transformer.transform(rec, schema)
        rec = fix_record_anytype(rec, schema)
        tap_output.write_record(
            (stream_alias or stream),
            rec,
            version=stream_version,
            time_extracted=start_time,
        )

        replication_key_value = replication_key and singer_utils.strptime_with_tz(rec[replication_key])

        if sf.is_pk_chunking(catalog_entry["tap_stream_id"]):
            if (
                replication_key_value
                and replication_key_value <= start_time
                and replication_key_value > chunked_bookmark
            ):
                # Replace the highest seen bookmark and save the state in case we need to resume later
                chunked_bookmark = singer_utils.strptime_with_tz(rec[replication_key])
                state = singer.write_bookmark(
                    state,
                    catalog_entry["tap_stream_id"],
                    "JobHighestBookmarkSeen",
                    tap_output.safe_bookmark_value(
                        stream, "JobHighestBookmarkSeen", singer_utils.strftime(chunked_bookmark),
                        max_future_seconds=CONFIG.get("max_future_bookmark_seconds", 3600)
                    ),
                )

                if counter.value % state_msg_threshold == 0:
                    tap_output.write_state(state)
        # Before writing a bookmark, make sure Salesforce has not given us a
        # record with one outside our range
        elif replication_key_value and replication_key_value <= start_time:
            state = singer.write_bookmark(
                state,
                catalog_entry["tap_stream_id"],
                replication_key,
                #tap_output.safe_bookmark_value(stream, replication_key, rec[replication_key]),
                tap_output.safe_bookmark_value(
                    stream, replication_key, rec[replication_key],
                    max_future_seconds=CONFIG.get("max_future_bookmark_seconds", 3600)
                ),
            )

            if counter.value % state_msg_threshold == 0:
                tap_output.write_state(state)

    if empty_filtered_window(sf, catalog_entry, counter, replication_key):
        LOGGER.info(
            "Filtered window for %s returned no rows; advancing bookmark to %s so the "
            "scanned range does not grow on the next run",
            stream,
            singer_utils.strftime(start_time),
        )
        # A PK-chunked stream writes its bookmark from chunked_bookmark at the end of
        # the stream, so that is set too. Both writes produce the same value, which is
        # why this does not need to know which path it is on.
        chunked_bookmark = start_time
        state = write_window_end_bookmark(state, catalog_entry, replication_key, start_time)

    # Tables with no replication_key will send an
    # activate_version message for the next sync
    if not replication_key:
        tap_output.write_message(activate_version_message)
        state = singer.write_bookmark(state, catalog_entry["tap_stream_id"], "version", None)

    # If this stream was PK-chunked, only write a bookmark at the end
    if sf.is_pk_chunking(catalog_entry["tap_stream_id"]):
        # Write a bookmark with the highest value we've seen
        state = singer.write_bookmark(
            state,
            catalog_entry["tap_stream_id"],
            replication_key,
            #tap_output.safe_bookmark_value(stream, replication_key, singer_utils.strftime(chunked_bookmark)),
            tap_output.safe_bookmark_value(
                stream, replication_key, singer_utils.strftime(chunked_bookmark),
                max_future_seconds=CONFIG.get("max_future_bookmark_seconds", 3600)
            ),
        )


def fix_record_anytype(rec, schema):
    """Modifies a record when the schema has no 'type' element due to a SF type of 'anyType.'
    Attempts to set the record's value for that element to an int, float, or string."""

    def try_cast(val, coercion):
        try:
            return coercion(val)
        except BaseException:
            return val

    for k, v in rec.items():
        if schema["properties"][k].get("type") is None:
            val = v
            val = try_cast(v, int)
            val = try_cast(v, float)
            if v in ["true", "false"]:
                val = v == "true"

            if v == "":
                val = None

            rec[k] = val

    return rec
